enum EventType {
  goPage,
  rateUs,
  httpError,
  getOfferingsError,
  getSubscriptionsError,
  onPurchaseStarted,
  onPurchaseCompleted,
  onPurchaseCompletedCatchError,
  onPurchaseError,
  onPurchaseCancelled,
  onRestoreCompleted,
  onRestoreCompletedCatchError,
  onRestoreError,
}
